name: generate_pdoc
# Event trigger
on:
  push:
    branches:
      - main
    paths:
      - "*.py"
  pull_request:
    branches:
      - main
    paths:
      - "*.py"
  workflow_dispatch:

jobs:
  generate_pdoc:
    name: generating pdoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # set up python
      - name: Setting up python.
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
        
      # install poetry
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      
      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      
      # install dependencies
      - name: Install Dependencies
        run: poetry install --no-interaction --no-dev

      # Generate document using pdoc
      - name: Pdoc
        run: poetry run pdoc --html -o docs --force sc18im700/sc18im700.py
      
      # push diffs to git
      # ref: https://zenn.dev/lollipop_onl/articles/eoz-gha-push-diffs
      - name: Push new docs
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Generating docs via GitHub Actions"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi